version: '3.8'

services:
  gpu_train_1:
    image: pytorch/pytorch:latest
    container_name: gpu_train_1
    command: bash -c "pip install transformers scikit-learn pandas && python /workspace/scripts/train.py"
    volumes:
      - .:/workspace

  gpu_train_2:
    image: pytorch/pytorch:latest
    container_name: gpu_train_2
    command: bash -c "pip install transformers scikit-learn pandas && python /workspace/scripts/train.py"
    volumes:
      - .:/workspace
