apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
  - name: debug-container
    image: ubuntu
    command: ["/bin/bash", "-c", "sleep infinity"]
    volumeMounts:
    - mountPath: "/app/models"
      name: model-storage
  volumes:
  - name: model-storage
    persistentVolumeClaim:
      claimName: model-pvc
