apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-trainer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: distributed-trainer
  template:
    metadata:
      labels:
        app: distributed-trainer
    spec:
      containers:
      - name: trainer
        image: deckwang/distributed-trainer:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/app/data"
          name: data-volume
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
