# For upload data file to PVC
apiVersion: v1
kind: Pod
metadata:
  name: pvc-uploader
spec:
  containers:
  - name: uploader
    image: ubuntu
    command: ["/bin/bash", "-c", "tail -f /dev/null"]
    volumeMounts:
    - mountPath: "/app/data"
      name: data-volume
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: data-pvc
  restartPolicy: Never
