apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: statefulset-deleter
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: statefulset-deleter-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: statefulset-deleter
  apiGroup: rbac.authorization.k8s.io
